openapi: 3.0.0
info:
  title: Gravitino API test
  description: Gravitino API demo
  version: 0.0.1
servers:
  - url: http://localhost:8090
paths:
  /api/metalakes:
    description: metalakes Response
    get:
      description: Returns a list of all metalakes.
      responses:
        200:
          description: Successs Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/metalakes'
components:
  schemas:
    metalakes:
      type: object
      properties:
        name:
          type: string
          example: metalake_demo
        comment:
          type: string
          example: comment
        audit:
          type: object
          properties:
            creator: 
              type: string
              example: anonymous
            createdTime:
              type: string
              example: "2024-02-26T18:11:13.777Z"
  
                      
                      
                      
                      
                      
                      
                      
                      
                      
      