# coding: utf-8

"""
    Gravitino API test

    Gravitino API demo  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MetalakesAudit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'creator': 'str',
        'created_time': 'str'
    }

    attribute_map = {
        'creator': 'creator',
        'created_time': 'createdTime'
    }

    def __init__(self, creator=None, created_time=None):  # noqa: E501
        """MetalakesAudit - a model defined in Swagger"""  # noqa: E501
        self._creator = None
        self._created_time = None
        self.discriminator = None
        if creator is not None:
            self.creator = creator
        if created_time is not None:
            self.created_time = created_time

    @property
    def creator(self):
        """Gets the creator of this MetalakesAudit.  # noqa: E501


        :return: The creator of this MetalakesAudit.  # noqa: E501
        :rtype: str
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this MetalakesAudit.


        :param creator: The creator of this MetalakesAudit.  # noqa: E501
        :type: str
        """

        self._creator = creator

    @property
    def created_time(self):
        """Gets the created_time of this MetalakesAudit.  # noqa: E501


        :return: The created_time of this MetalakesAudit.  # noqa: E501
        :rtype: str
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this MetalakesAudit.


        :param created_time: The created_time of this MetalakesAudit.  # noqa: E501
        :type: str
        """

        self._created_time = created_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MetalakesAudit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetalakesAudit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
