# coding: utf-8

"""
    Gravitino API test

    Gravitino API demo  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.metalakes import Metalakes  # noqa: E501
from swagger_client.rest import ApiException


class TestMetalakes(unittest.TestCase):
    """Metalakes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetalakes(self):
        """Test Metalakes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.metalakes.Metalakes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
